baseURL = 'http://localhost'
languageCode = 'en-us'
title = 'Asif Mammadov'

name = "Gruvbox"
license = "MIT"
licenselink = "https://github.com/schnerring/hugo-theme-gruvbox/blob/main/LICENSE"
description = "A retro-looking Hugo theme inspired by the gruvbox. The pastel colors are high contrast, easily distinguishable, pleasing to the eye, and feature light and dark color palettes."
homepage = "https://github.com/schnerring/hugo-theme-gruvbox"
demosite = "https://hugo-theme-gruvbox.schnerring.net"
tags = [
  "blog",
  "dark mode",
  "minimal",
  "personal",
  "responsive"
]
features = ["dark mode"]
min_version = "0.41.0"

[author]
  name = "Michael Schnerring"
  homepage = "https://schnerring.net"


[markup]
  # (Optional) To be able to use all Prism plugins, the theme enables unsafe
  # rendering by default
  #_merge = "deep"

[build]
  # The theme enables writeStats which is required for PurgeCSS
  _merge = "deep"

# This hopefully will be simpler in the future.
# See: https://github.com/schnerring/hugo-theme-gruvbox/issues/16
[module]
  [[module.imports]]
    path = "github.com/schnerring/hugo-mod-github-readme-stats"
  [[module.imports]]
    path = "github.com/schnerring/hugo-mod-json-resume"
    [[module.imports.mounts]]
      source = "data"
      target = "data"
    [[module.imports.mounts]]
      source = "layouts"
      target = "layouts"
    [[module.imports.mounts]]
      source = "assets/css/json-resume.css"
      target = "assets/css/critical/44-json-resume.css"
  [[module.mounts]]
    # required by hugo-mod-json-resume
    source = "node_modules/simple-icons/icons"
    target = "assets/simple-icons"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.mounts]]
    source = "node_modules/prismjs"
    target = "assets/prismjs"
  [[module.mounts]]
    source = "node_modules/prism-themes/themes"
    target = "assets/prism-themes"
  [[module.mounts]]
    source = "node_modules/typeface-fira-code/files"
    target = "static/fonts"
  [[module.mounts]]
    source = "node_modules/typeface-roboto-slab/files"
    target = "static/fonts"
  [[module.mounts]]
    source = "node_modules/@tabler/icons/icons"
    target = "assets/tabler-icons"


[menu]
  [[menu.main]]
    identifier = "cv"
    name = "CV"
    url = "/"
    weight = 30
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 40
  [[menu.main]]
    identifier = "stats"
    name = "Stats"
    url = "/stats"
    weight = 50
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 60